list_of_users = ['Farshid', 'Elham', 'Arshida', 'Avina']
print(list_of_users)
list_of_users.append('Farnia')
print(list_of_users)
list_of_users.insert(4, 'Shafiei')
print(list_of_users)
list_of_users.remove('Shafiei')
print(list_of_users)
list_of_users.pop()
print(list_of_users)
list_of_users.clear()
print(list_of_users)
numbers = [0, 2, 4, 1, 3, 5, 0, 2, 0]
print(numbers.index(0))
print(14 in numbers)
print(numbers.count(0))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers = list(dict.fromkeys(numbers))
print(numbers)